export const ROOT_FOOTER_DATA = [
  { id: "about", text: "About" },
  { id: "help", text: "Help Center" },
  { id: "tos", text: "Terms of Service" },
  { id: "private", text: "Privacy Policy" },
  { id: "cookie", text: "Cookie Policy" },
  { id: "ads", text: "Ads Info" },
  { id: "blog", text: "Blog" },
  { id: "status", text: "Status" },
  { id: "brand", text: "Brand Resources" },
  { id: "adverts", text: "Advertising" },
  { id: "market", text: "Marketing" },
  { id: "business", text: "Twitter for Business" },
  { id: "devs", text: "Developers" },
  { id: "dir", text: "Directory" },
  { id: "settings", text: "Settings" },
];
